name: Update Main Repo
on:
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v3
        with:
          repository: spencer0124/web-tools
          token: ${{ secrets.AUTO_ACTION_TOKEN }}
          submodules: recursive
      - name: Update Submodule
        run: |
          git config user.email "action@github.com"
          git config user.name "Auto Bot"
          git submodule update --remote ig-carousel
          git add ig-seamless-carousel
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update ig-seamless-carousel tool" && git push)
